/*-------------------------------------------------------------------------
    This file is part of Nucleo.js

    Nucleo is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation version 3.

    Nucleo is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Nucleo.  If not, see <http://www.gnu.org/licenses/>.
---------------------------------------------------------------------------*/   
try{
    if (!jQuery){
    	alert('Nucleo: jQuery is not loaded. Please include JQuery in your page');
    }
}catch(e){
    alert('Nucleo: jQuery is not loaded. Please include JQuery in your page');
}


/**
* <p>Contains all the constants and default variables used by Nucleo.</p>
* 
* <p> These properties aregrouped into sub namespaces. 
* The <code>nucleo.c</code> namespace covers all the 'current' objects such as the
* <i>current view</i> and the <i>current scene</i>.</p>
* <p>The <code>nucleo.def</code> namespace contains all the definitions and default values for
* Nucleo's global parameters</p>
* <p>The <code>define.EVENTS</code> namespace contains all the events used in Nucleo</p>
* <p>The <code>nucleo.go</code> namespace contains all the 'global' objects. These are objects that
* can be accessed from any context in a Nucleo program</p>
* <p>The <code>nucleo.version</code> namespace simply informs the version of the current Nucleo platform</p>
* 
* @namespace Nucleo Main Namespace
* @property {nucleo.c}         c           current objects
* @property {nucleo.def}       def         definition objects
* @property {define.EVENTS}    events      events generated by Nucleo
* @property {nucleo.go}        go          global objects
* @property {nucleo.version}   version     version
* 
*/
var vxl = {

/**
* Version
* @namespace Nucleo Version
* @property {String} number         the number of the current version
* @property {String} codename       the codename of the current version
* @property {Array}  plugins        installed plugins if any
*/
version : 
{
    number: '0.90.2',
   	codename : 'c4n314',
   	plugins  : []
},

/**
 * @namespace Nucleo Default/Definition Objects
 * @property {nucleo.def.essl}     essl    ESSL constants
 * @property {nucleo.def.lut}      lut     Lookup Table Definitions
 * @property {nucleo.def.model}    model   Default          values for models
 * @property {nucleo.def.view}     view    Default values for views
 * 
 */
def : {
  

    /


    /



				 	

	

					

},






